split1

In [1]:
split = 'split1'
path = "../5-fold_new/DATA/"
train_path = "{}/{}/train/train_{}.csv".format(path,split,split)
test_path =  "{}/test.csv".format(path)
val_path = "{}/{}/val/val_{}.csv".format(path,split,split)

print(train_path)
print(test_path)
print(val_path)

../5-fold_new/DATA//split1/train/train_split1.csv
../5-fold_new/DATA//test.csv
../5-fold_new/DATA//split1/val/val_split1.csv


In [2]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

# Load the training set
train_data = pd.read_csv(train_path)
print(train_data.shape)
x_train = train_data[train_data.columns[2:]]
print(x_train.shape)
y_train = train_data[train_data.columns[1]]
le = LabelEncoder()
y_train = np.array(le.fit_transform(y_train))
print(le.classes_)
print('\n')

# Load the testing set
test_data = pd.read_csv(test_path)
print(test_data.shape)
x_test = test_data[test_data.columns[3:]]
print(x_test.shape)
y_test = test_data[test_data.columns[2]]
le = LabelEncoder()
y_test = np.array(le.fit_transform(y_test))
print(le.classes_)
print('\n')

# Load the validation set
val_data = pd.read_csv(val_path)
print(val_data.shape)
x_val = val_data[val_data.columns[2:]]
print(x_val.shape)
y_val = val_data[val_data.columns[1]]
le = LabelEncoder()
y_val = np.array(le.fit_transform(y_val))
print(le.classes_)
print('\n')

print("Shape of training set:", x_train.shape)
print("Shape of testing set:", x_test.shape)

(364, 32)
(364, 30)
['B' 'M']


(114, 33)
(114, 30)
['B' 'M']


(91, 32)
(91, 30)
['B' 'M']


Shape of training set: (364, 30)
Shape of testing set: (114, 30)


In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

logreg = LogisticRegression(solver='lbfgs', max_iter=3000)
logreg.fit(x_train, y_train)
predictions = logreg.predict(x_test)

print("Confusion Matrix: \n", confusion_matrix(y_test, predictions))
print('\n')
print(classification_report(y_test, predictions))

logreg_acc = accuracy_score(y_test, predictions)
print("Accuracy of the Logistic Regression Model is: ", logreg_acc)

Confusion Matrix: 
 [[46  0]
 [12 56]]


              precision    recall  f1-score   support

           0       0.79      1.00      0.88        46
           1       1.00      0.82      0.90        68

    accuracy                           0.89       114
   macro avg       0.90      0.91      0.89       114
weighted avg       0.92      0.89      0.90       114

Accuracy of the Logistic Regression Model is:  0.8947368421052632


split2

In [4]:
split = 'split2'
path = "../5-fold_new/DATA/"
train_path = "{}/{}/train/train_{}.csv".format(path,split,split)
test_path =  "{}/test.csv".format(path)
val_path = "{}/{}/val/val_{}.csv".format(path,split,split)

# Load the training set
train_data = pd.read_csv(train_path)
print(train_data.shape)
x_train = train_data[train_data.columns[2:]]
print(x_train.shape)
y_train = train_data[train_data.columns[1]]
le = LabelEncoder()
y_train = np.array(le.fit_transform(y_train))
print(le.classes_)
print('\n')

# Load the testing set
test_data = pd.read_csv(test_path)
print(test_data.shape)
x_test = test_data[test_data.columns[3:]]
print(x_test.shape)
y_test = test_data[test_data.columns[2]]
le = LabelEncoder()
y_test = np.array(le.fit_transform(y_test))
print(le.classes_)
print('\n')

# Load the validation set
val_data = pd.read_csv(val_path)
print(val_data.shape)
x_val = val_data[val_data.columns[2:]]
print(x_val.shape)
y_val = val_data[val_data.columns[1]]
le = LabelEncoder()
y_val = np.array(le.fit_transform(y_val))
print(le.classes_)

(364, 32)
(364, 30)
['B' 'M']


(114, 33)
(114, 30)
['B' 'M']


(91, 32)
(91, 30)
['B' 'M']


In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

logreg = LogisticRegression(solver='lbfgs', max_iter=3000)
logreg.fit(x_train, y_train)
predictions = logreg.predict(x_test)

print("Confusion Matrix: \n", confusion_matrix(y_test, predictions))
print('\n')
print(classification_report(y_test, predictions))

logreg_acc = accuracy_score(y_test, predictions)
print("Accuracy of the Logistic Regression Model is: ", logreg_acc)

Confusion Matrix: 
 [[46  0]
 [ 9 59]]


              precision    recall  f1-score   support

           0       0.84      1.00      0.91        46
           1       1.00      0.87      0.93        68

    accuracy                           0.92       114
   macro avg       0.92      0.93      0.92       114
weighted avg       0.93      0.92      0.92       114

Accuracy of the Logistic Regression Model is:  0.9210526315789473


split3

In [6]:
split = 'split3'
path = "../5-fold_new/DATA/"
train_path = "{}/{}/train/train_{}.csv".format(path,split,split)
test_path =  "{}/test.csv".format(path)
val_path = "{}/{}/val/val_{}.csv".format(path,split,split)

# Load the training set
train_data = pd.read_csv(train_path)
print(train_data.shape)
x_train = train_data[train_data.columns[2:]]
print(x_train.shape)
y_train = train_data[train_data.columns[1]]
le = LabelEncoder()
y_train = np.array(le.fit_transform(y_train))
print(le.classes_)
print('\n')

# Load the testing set
test_data = pd.read_csv(test_path)
print(test_data.shape)
x_test = test_data[test_data.columns[3:]]
print(x_test.shape)
y_test = test_data[test_data.columns[2]]
le = LabelEncoder()
y_test = np.array(le.fit_transform(y_test))
print(le.classes_)
print('\n')

# Load the validation set
val_data = pd.read_csv(val_path)
print(val_data.shape)
x_val = val_data[val_data.columns[2:]]
print(x_val.shape)
y_val = val_data[val_data.columns[1]]
le = LabelEncoder()
y_val = np.array(le.fit_transform(y_val))
print(le.classes_)

(364, 32)
(364, 30)
['B' 'M']


(114, 33)
(114, 30)
['B' 'M']


(91, 32)
(91, 30)
['B' 'M']


In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

logreg = LogisticRegression(solver='lbfgs', max_iter=3000)
logreg.fit(x_train, y_train)
predictions = logreg.predict(x_test)

print("Confusion Matrix: \n", confusion_matrix(y_test, predictions))
print('\n')
print(classification_report(y_test, predictions))

logreg_acc = accuracy_score(y_test, predictions)
print("Accuracy of the Logistic Regression Model is: ", logreg_acc)

Confusion Matrix: 
 [[46  0]
 [10 58]]


              precision    recall  f1-score   support

           0       0.82      1.00      0.90        46
           1       1.00      0.85      0.92        68

    accuracy                           0.91       114
   macro avg       0.91      0.93      0.91       114
weighted avg       0.93      0.91      0.91       114

Accuracy of the Logistic Regression Model is:  0.9122807017543859


split4

In [8]:
split = 'split4'
path = "../5-fold_new/DATA/"
train_path = "{}/{}/train/train_{}.csv".format(path,split,split)
test_path =  "{}/test.csv".format(path)
val_path = "{}/{}/val/val_{}.csv".format(path,split,split)

# Load the training set
train_data = pd.read_csv(train_path)
print(train_data.shape)
x_train = train_data[train_data.columns[2:]]
print(x_train.shape)
y_train = train_data[train_data.columns[1]]
le = LabelEncoder()
y_train = np.array(le.fit_transform(y_train))
print(le.classes_)
print('\n')

# Load the testing set
test_data = pd.read_csv(test_path)
print(test_data.shape)
x_test = test_data[test_data.columns[3:]]
print(x_test.shape)
y_test = test_data[test_data.columns[2]]
le = LabelEncoder()
y_test = np.array(le.fit_transform(y_test))
print(le.classes_)
print('\n')

# Load the validation set
val_data = pd.read_csv(val_path)
print(val_data.shape)
x_val = val_data[val_data.columns[2:]]
print(x_val.shape)
y_val = val_data[val_data.columns[1]]
le = LabelEncoder()
y_val = np.array(le.fit_transform(y_val))
print(le.classes_)

(364, 32)
(364, 30)
['B' 'M']


(114, 33)
(114, 30)
['B' 'M']


(91, 32)
(91, 30)
['B' 'M']


In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

logreg = LogisticRegression(solver='lbfgs', max_iter=3000)
logreg.fit(x_train, y_train)
predictions = logreg.predict(x_test)

print("Confusion Matrix: \n", confusion_matrix(y_test, predictions))
print('\n')
print(classification_report(y_test, predictions))

logreg_acc = accuracy_score(y_test, predictions)
print("Accuracy of the Logistic Regression Model is: ", logreg_acc)

Confusion Matrix: 
 [[46  0]
 [ 9 59]]


              precision    recall  f1-score   support

           0       0.84      1.00      0.91        46
           1       1.00      0.87      0.93        68

    accuracy                           0.92       114
   macro avg       0.92      0.93      0.92       114
weighted avg       0.93      0.92      0.92       114

Accuracy of the Logistic Regression Model is:  0.9210526315789473


split5

In [10]:
split = 'split5'
path = "../5-fold_new/DATA/"
train_path = "{}/{}/train/train_{}.csv".format(path,split,split)
test_path =  "{}/test.csv".format(path)
val_path = "{}/{}/val/val_{}.csv".format(path,split,split)

# Load the training set
train_data = pd.read_csv(train_path)
print(train_data.shape)
x_train = train_data[train_data.columns[2:]]
print(x_train.shape)
y_train = train_data[train_data.columns[1]]
le = LabelEncoder()
y_train = np.array(le.fit_transform(y_train))
print(le.classes_)
print('\n')

# Load the testing set
test_data = pd.read_csv(test_path)
print(test_data.shape)
x_test = test_data[test_data.columns[3:]]
print(x_test.shape)
y_test = test_data[test_data.columns[2]]
le = LabelEncoder()
y_test = np.array(le.fit_transform(y_test))
print(le.classes_)
print('\n')

# Load the validation set
val_data = pd.read_csv(val_path)
print(val_data.shape)
x_val = val_data[val_data.columns[2:]]
print(x_val.shape)
y_val = val_data[val_data.columns[1]]
le = LabelEncoder()
y_val = np.array(le.fit_transform(y_val))
print(le.classes_)

(364, 32)
(364, 30)
['B' 'M']


(114, 33)
(114, 30)
['B' 'M']


(91, 32)
(91, 30)
['B' 'M']


In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

logreg = LogisticRegression(solver='lbfgs', max_iter=3000)
logreg.fit(x_train, y_train)
predictions = logreg.predict(x_test)

print("Confusion Matrix: \n", confusion_matrix(y_test, predictions))
print('\n')
print(classification_report(y_test, predictions))

logreg_acc = accuracy_score(y_test, predictions)
print("Accuracy of the Logistic Regression Model is: ", logreg_acc)

Confusion Matrix: 
 [[46  0]
 [10 58]]


              precision    recall  f1-score   support

           0       0.82      1.00      0.90        46
           1       1.00      0.85      0.92        68

    accuracy                           0.91       114
   macro avg       0.91      0.93      0.91       114
weighted avg       0.93      0.91      0.91       114

Accuracy of the Logistic Regression Model is:  0.9122807017543859
